### ISSUE TITLE
Extract training code as a Trainer class instance for testable code

### ISSUE THREAD

**Issue by metric-space** [arcee-ai/DALM#32]
### What needs to be done
Either

- [ ] Make a base trainer class similar to [trl's base trainer](https://github.com/huggingface/trl/blob/main/trl/trainer/base.py#L18) 
- [ ] Mold code in `train_rage2e.py` as said base trainer class instance

OR

take the functional approach of breaking down code into multiple functions

### Reason for proposal
The hope is to make the code more amenable to  testing

**Comment by tleyden** [comment]
In attempt to clean up issues, I'm closing this as WONTDO for now.  We can reprioritize for later as needed.
