### ISSUE TITLE
Add docs for `retriever_only` 

### ISSUE THREAD

**Issue by Ben-Epstein** [arcee-ai/DALM#34]
we have great docs for the [e2e code](https://github.com/arcee-ai/DALM/blob/feat/open-source-prep/dalm/training/rag_e2e/README.md) but nothing for the [retriever-only section](https://github.com/arcee-ai/DALM/blob/feat/open-source-prep/dalm/training/retriever_only/README.md) 

Let's add something short there. It doesn't need to be particularly verbose because the root readme is really good already

**Comment by SachiraKuruppu** [comment]
I can pick this up if @shamanez is busy

**Comment by shamanez** [comment]
Sure

**Comment by tleyden** [comment]
In attempt to clean up issues, I'm closing this as WONTDO for now.  We can reprioritize for later as needed.
