### ISSUE TITLE
Minimum system requirements to train

### ISSUE THREAD

**Issue by pribadihcr** [arcee-ai/DALM#58]
Hi, What are the minimum system requirements like GPU memory to train rag_e2e?. Thanks

**Comment by shamanez** [comment]
Depends on your model size and the batch size.

We managed to train a large baai sentence transformer and a 7b llama
generator with a batch size of 18 using a single A100 which is 80GB.

**Comment by pribadihcr** [comment]
How long did it take to train using the dataset?

**Comment by shamanez** [comment]
We used 200K examples and took like 7 hrs.

**Comment by Ben-Epstein** [comment]
closing as we've added the requirements to the readme. thanks @pribadihcr !
