### ISSUE TITLE
Eval e2e Rag raising device mismatch error

### ISSUE THREAD

**Issue by sagorbrur** [arcee-ai/DALM#73]
Hi,
After training `rag_e2e` I am facing a device mismatch problem for evaluating the model by `eval_rag.py`. 
My evaluation command is:
```bash
python dalm/eval/eval_rag.py  \
 --dataset_path ./dalm/datasets/toy_data_train.csv \
 --retriever_name_or_path "myretriever" \
 --generator_name_or_path "mygenerator" \
 --passage_column_name Abstract \
 --query_column_name Question \
 --answer_column_name Answer \
 --evaluate_generator \
 --query_batch_size 5
```
Error I am getting:
```bash
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

After debuging I figure out the [AutoModelForRagE2E](https://github.com/arcee-ai/DALM/blob/e6c3d293e7c75a43a6cfb3d78681969c1219e8c8/dalm/models/rag_e2e_base_model.py#L22) is CPU based.
If I convert the  `AutoModelForRagE2E` load model to "cuda" then it works fine. 
Mybe inside the `AutoModelForRagE2E` while loading the retriever and generator we need to convert the load model to CUDA. 
Should I do this and send a pull request or am I missing something? 
Please let me know. 

Kind regards

**Comment by shamanez** [comment]
@sagorbrur 

Thank you for pointing this out. I've identified the issue: we are not assigning the retriever and generator models to the device. Currently, we only use `to(device)` for [pre-trained peft layers](https://github.com/arcee-ai/DALM/blob/main/dalm/eval/eval_rag.py#L198).

A simpler solution would be to insert the following lines [after loading the models](https://github.com/arcee-ai/DALM/blob/main/dalm/eval/eval_rag.py#L198C73-L198C98).

```
if retriever_peft_model_path is none:
      rag_model.retriever_model.eval().to(device)
if generator_peft_model_path is none:
     rag_model.generator_model.eval().to(device)
```
feel free to send a PR!!!!

**Comment by sagorbrur** [comment]
@shamanez ,
Thanks for the details explanation. 
I will add that part and send the PR soon.

Regards
