### ISSUE TITLE
DALM installation fails in my python environment.

### ISSUE THREAD

**Issue by Aekansh-Ak** [arcee-ai/DALM#87]
P.F.A. the image.
The error comes after pip install --upgrade -q -e .

![image](https://github.com/arcee-ai/DALM/assets/64459173/501fc6ac-acdb-4cdd-8fa7-8ad15d1e6bc4)

**Comment by tleyden** [comment]
Hey @Aekansh-Ak.  Yes that's a known issue.  I just merged a fix for it in https://github.com/arcee-ai/DALM/pull/86

Can you pull the latest from main and try again?

Also, yes python 3.10 is required.  In the project.toml file you can see the line `requires-python = ">=3.10"`
